spring:
  application:
    name: api--wishlist
  data:
    mongodb:
      uri: mongodb://root:1235!@localhost:27017
      database: wishlist
    redis:
      host: localhost
      port: 6379
      database: 0
      password: 1235

wishlist:
  limit-size: 20

redis:
  host: localhost
  password: 1235
  port: 6379

sonar:
  host:
    url: http://localhost:9000
  jdbc:
    url: jdbc:h2:tcp://localhost:9092/sonar
    username: wish
    password: 1235

